---
abstract: 'Lite Web Application Framework'
author:
  - 'Lepenkov Sergey (Serz Minus) <minus@mail333.com>'
build_requires:
  ExtUtils::MakeMaker: 6.6
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MLite
no_index:
  directory:
    - t
    - inc
recommends:
  DBI: 0
  Data::Dumper: 0
requires:
  CTK: 1.16
  DBI: 0
  Digest::MD5: 2.36
  Module::Load: 0
  perl: 5.008001
resources:
  homepage: http://www.serzik.com
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://svn.serzik.com/WWW-MLite/trunk
version: 1.02
